name: attendance
description: "Attendance register."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.0
  dio: ^5.5.0+1
  logger: ^2.3.0
  get_it: ^8.0.3
  hive: ^2.2.3
  pretty_dio_logger: ^1.3.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.2
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.1.1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  syncfusion_flutter_datagrid: ^28.2.4
  intl: ^0.19.0
  drift: ^2.19.1+1
  drift_flutter: ^0.2.4
  path: ^1.9.0
  sqflite: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.7
  hive_generator: ^2.0.1
  drift_dev: ^2.19.1

dependency_overrides:
  win32: 5.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/